[default]
src = 'contracts'
test = 'tests'
remappings = [
  "OpenZeppelin/openzeppelin-contracts@02fcc75bb7f35376c22def91b0fb9bc7a50b9458/=./lib/openzeppelin-contracts",
  "OpenZeppelin/openzeppelin-contracts-upgradeable@a16f26a063cd018c4c986832c3df332a131f53b9/=./lib/openzeppelin-contracts-upgradeable",
  "OpenZeppelin/openzeppelin-contracts@4.6.0/=./lib/openzeppelin-contracts",
  "OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0/=./lib/openzeppelin-contracts-upgradeable",
  "paulrberg/prb-math@2.5.0/=./lib/prb-math"
]
