// autogenerated by brownie
// do not modify the existing settings
// from here: https://github.com/eth-brownie/brownie/blob/d036516930eaa250aa2764b9719ae40e89f93409/brownie/network/rpc/hardhat.py#L23-L37
module.exports = {
  networks: {
    hardhat: {
      hardfork: "london",
      // base fee of 0 allows use of 0 gas price when testing
      initialBaseFeePerGas: 0,
      // brownie expects calls and transactions to throw on revert
      throwOnTransactionFailures: true,
      throwOnCallFailures: true,
      accounts: {
        mnemonic:
          "there reopen orchard damage width skirt resource clap device idle tag twelve",
        count: 100
      },
    },
  },
};
