name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "client"
          usedocker: true
          docker_build_args: |
            DATABASE_URL
            NEXT_PUBLIC_NETWORK_ID
          docker_heroku_process_type: "web, listener"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_NETWORK_ID: 4
