import { FunctionComponent, Dispatch, SetStateAction } from "react";
import TokenIcon from "components/TokenIcon";
import Video from "components/Video";
import Card from "components/Card";
import CardGroup from "components/CardGroup";
import Quiz from "components/claim/education/Quiz";

interface OgnProps {
  handleNextStep: () => void;
}

const questions = [
  {
    question:
      "Which of the following is NOT a product offering of Origin Story?",
    answers: [
      "NFT minting",
      "Branded, collection-specific marketplace on a creator's own domain",
      "Token-gated access to exclusive experiences",
      "NFT borrowing and lending",
    ],
    correctAnswer: "NFT borrowing and lending",
  },
  {
    question:
      "Which of the following is the value accrual token for Origin Story?",
    answers: ["OUSD", "OGV", "OGN", "DOGE"],
    correctAnswer: "OGN",
  },
  {
    question: "Which of the following will OGN stakers be entitled to?",
    answers: [
      "Fees generated by Origin Story primary sales (NFT mints)",
      "Fees generated by Origin Story secondary royalties",
      "Fees generated by Origin Story secondary marketplace fees",
      "100% of the fees generated by Origin Story",
    ],
    correctAnswer: "100% of the fees generated by Origin Story",
  },
];

const Ogn: FunctionComponent<OgnProps> = ({ handleNextStep }) => (
  <CardGroup>
    <Card>
      <div className="space-y-4">
        <div className="flex items-center space-x-1">
          <TokenIcon src="/ogn-coin.svg" alt="OGN" />
          <h3 className="text-lg leading-6 font-medium">Origin Token (OGN)</h3>
        </div>
        <Video id="5r_GV4CVvXU" />
        <div className="text-sm lg:text-base text-gray-800 space-y-4">
          <p>
            OGN is your key to earning ETH rewards from the Origin Story
            platform, which has powered record-breaking NFT drops from 3LAU,
            Paris Hilton, BT, Trevor Jones, Don Diablo, and more.
          </p>
          <p>
            Our mission is to bring NFTs to everyone with the simplest and most
            trusted way for creators to launch and grow their NFT communities
            and collections.
          </p>
          <p>
            Origin Story lowers the barriers of entry for creators to mint their
            first NFTs and create more value for their collectors.
          </p>
          <p>
            With OGN, Origin Story&apos;s dedicated value accrual token, you get
            a piece of the action.
          </p>
          <p>
            That means you can buy OGN tokens and stake them to earn part of the
            commissions that Origin Story makes on NFT primary and secondary
            sales.
          </p>
          <p>
            With Origin Story rapidly expanding its platform to include trusted
            official marketplaces, token-gated access to exclusive experiences,
            and more, OGN token holders will also benefit as the Origin Story
            platform grows.
          </p>
        </div>
      </div>
    </Card>
    <Card>
      <Quiz questions={questions} lastQuiz handleNextStep={handleNextStep} />
    </Card>
  </CardGroup>
);

export default Ogn;
