import { FunctionComponent, Dispatch, SetStateAction } from "react";
import TokenIcon from "components/TokenIcon";
import Video from "components/Video";
import Card from "components/Card";
import CardGroup from "components/CardGroup";
import Quiz from "components/claim/education/Quiz";

interface OgnProps {
  onComplete?: Dispatch<SetStateAction<boolean>>;
}

const questions = [
  {
    question:
      "Which of the following is NOT a product offering of Origin Story?",
    answers: [
      "NFT minting",
      "Branded, collection-specific marketplace on a creator's own domain",
      "Token-gated access to exclusive experiences",
      "NFT borrowing and lending",
    ],
    correctAnswer: "NFT borrowing and lending",
  },
  {
    question:
      "Which of the following is the governance token for Origin Story?",
    answers: ["OUSD", "OGV", "OGN", "DOGE"],
    correctAnswer: "OGN",
  },
  {
    question: "Which of the following will OGN stakers be entitled to?",
    answers: [
      "Fees generated by Origin Story primary sales (NFT mints)",
      "Fees generated by Origin Story secondary royalties",
      "Fees generated by Origin Story secondary marketplace fees",
      "All of the above",
    ],
    correctAnswer: "All of the above",
  },
];

const Ogn: FunctionComponent<OgnProps> = ({ onComplete }) => (
  <CardGroup>
    <Card>
      <div className="space-y-4">
        <div className="flex items-center space-x-1">
          <TokenIcon src="/ogn-coin.svg" alt="OGN" />
          <h3 className="text-lg leading-6 font-medium">
            Origin Story Governance (OGN)
          </h3>
        </div>
        <Video />
        <div className="text-sm lg:text-base text-gray-600 space-y-4">
          <p>
            With the introduction of OGV, the Origin Token (OGN) becomes the
            dedicated governance token for Origin Story, the NFT platform that
            has powered record-breaking NFT drops from world-renowned creators
            including 3LAU, Paris Hilton, BT, Trevor Jones, and Don Diablo.
            Since early 2021, Origin Story has been at the forefront of defining
            new NFT use cases and empowering creators to bring their audiences
            to Web3. Origin Story’s mission is to bring NFTs to the masses with
            the simplest and most trusted way for NFT creators to launch, manage
            and grow their collections and communities.
          </p>
          <p>
            The Story platform dramatically lowers the barriers of entry for
            creators to mint their first NFT and continually create more value
            for their collectors. Story offers a full suite of products to help
            creators run successful NFT projects and communities, including NFT
            minting, branded marketplaces, and exclusive token-gated experiences
            for NFT holders. Creators can mint NFT collections within minutes,
            and launch a branded, collection-specific marketplace on their own
            domain to drive secondary sales in a trusted and secure way.
          </p>
          <p>
            As Origin Story transitions to decentralized governance, OGN holders
            will have the opportunity to stake their tokens for a share of Story
            platform revenues. Origin Story generates fees from commissions on
            primary sales (NFT mints) and fees/royalties from secondary trading.
            OGN holders who stake their OGN tokens will receive ETH rewards
            representing a share of all fees generated by the Story platform.{" "}
          </p>
        </div>
      </div>
    </Card>
    <Card>
      <Quiz
        questions={questions}
        onComplete={onComplete}
        onCompleteMessage="Continue to learn about OGV"
      />
    </Card>
  </CardGroup>
);

export default Ogn;
