import { FunctionComponent, Dispatch, SetStateAction } from "react";
import TokenIcon from "components/TokenIcon";
import Video from "components/Video";
import Card from "components/Card";
import CardGroup from "components/CardGroup";
import Quiz from "components/claim/education/Quiz";

interface OgvProps {
  onComplete?: Dispatch<SetStateAction<boolean>>;
}

const questions = [
  {
    question: "Which of the following is the governance token for OUSD?",
    answers: ["OGN", "OGV", "GOV", "ODG"],
    correctAnswer: "OGV",
  },
  {
    question: "Which is the best reason to lock OGV and convert it to veOGV?",
    answers: [
      "To keep it from being burned",
      "veOGV is freely transferable",
      "To hedge against Bitcoin",
      "veOGV holders earn fees from OUSD's yield and staking rewards",
    ],
    correctAnswer:
      "veOGV holders earn fees from OUSD's yield and staking rewards",
  },
  {
    question: "How can you earn more as OUSD adoption increases?",
    answers: [
      "Wait to claim OGV after OUSD succeeds",
      "Lock OGV now to get fees and voting power",
    ],
    correctAnswer: "Lock OGV now to get fees and voting power",
  },
];

const Ogv: FunctionComponent<OgvProps> = ({ onComplete }) => (
  <CardGroup>
    <Card>
      <div className="space-y-4">
        <div className="flex items-center space-x-1">
          <TokenIcon src="/ogv.svg" alt="OGV" />
          <h3 className="text-lg leading-6 font-medium">
            Origin Dollar Governance (OGV)
          </h3>
        </div>
        <Video id="5r_GV4CVvXU" />
        <div className="text-sm lg:text-base text-gray-800 space-y-4">
          <p>Congratulations, you&apos;re ready to claim your OGV airdrop.</p>
          <p>
            OGV lets you own a piece of the future growth of OUSD. You can claim
            OGV and lock it for up for anywhere from 1 week to 4 years to
            maximize your earnings and voting power.
          </p>
          <p>
            When OGV is locked, it&apos;s converted into veOGV (or
            “vote-escrowed OGV”) and it becomes non-transferable but it earns
            fees as OUSD adoption grows.
          </p>
          <p>
            As a veOGV holder, your vote impacts the future of OUSD. You decide
            whether to support new collateral types, adjust staking rewards, and
            more.
          </p>
          <p>
            On day one, veOGV holders can claim 10% of the yield generated by
            the protocol. As OUSD adoption accelerates, the benefits accrue to
            the holders of veOGV.
          </p>
          <p>
            To sum it up, we&apos;re thinking long-term and rewarding those who
            are here for the long-run.
          </p>
        </div>
      </div>
    </Card>
    <Card>
      <Quiz
        questions={questions}
        onComplete={onComplete}
        onCompleteMessage="Continue to learn about OGN"
      />
    </Card>
  </CardGroup>
);

export default Ogv;
